// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_0837_vsc_0_MultiPixStream2AXIvideo (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        OutYUV_dout,
        OutYUV_empty_n,
        OutYUV_read,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        Height_dout,
        Height_empty_n,
        Height_read,
        Width_dout,
        Width_empty_n,
        Width_read,
        ColorMode_dout,
        ColorMode_empty_n,
        ColorMode_read
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state7 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] OutYUV_dout;
input   OutYUV_empty_n;
output   OutYUV_read;
output  [23:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input  [9:0] Height_dout;
input   Height_empty_n;
output   Height_read;
input  [10:0] Width_dout;
input   Width_empty_n;
output   Width_read;
input  [7:0] ColorMode_dout;
input   ColorMode_empty_n;
output   ColorMode_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg OutYUV_read;
reg Height_read;
reg Width_read;
reg ColorMode_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    OutYUV_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln938_reg_499;
reg    m_axis_video_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln938_reg_499_pp0_iter1_reg;
reg    Height_blk_n;
reg    Width_blk_n;
reg    ColorMode_blk_n;
reg   [10:0] j_reg_180;
reg   [0:0] sof_3_reg_191;
reg   [7:0] ColorMode_read_reg_457;
wire   [9:0] trunc_ln897_fu_262_p1;
reg   [9:0] trunc_ln897_reg_461;
wire    ap_CS_fsm_state2;
wire   [10:0] grp_reg_unsigned_short_s_fu_251_ap_return;
reg   [10:0] cols_reg_466;
wire   [11:0] sub_i_fu_270_p2;
reg   [11:0] sub_i_reg_471;
wire   [0:0] cmp19184_i_fu_276_p2;
reg   [0:0] cmp19184_i_reg_476;
wire   [9:0] i_1_fu_282_p2;
reg   [9:0] i_1_reg_480;
wire    ap_CS_fsm_state3;
wire    regslice_both_AXI_video_strm_V_data_V_U_apdone_blk;
wire   [0:0] icmp_ln936_fu_291_p2;
wire   [10:0] j_1_fu_296_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_state5_io;
reg    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_state6_io;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln938_fu_306_p2;
wire   [0:0] icmp_ln951_fu_311_p2;
reg   [0:0] icmp_ln951_reg_503;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg    ap_condition_pp0_exit_iter1_state5;
wire   [10:0] grp_reg_unsigned_short_s_fu_245_d;
wire   [10:0] grp_reg_unsigned_short_s_fu_245_ap_return;
reg   [9:0] i_reg_169;
wire    ap_CS_fsm_state7;
reg   [0:0] ap_phi_mux_sof_3_phi_fu_196_p4;
reg   [23:0] ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6;
wire   [23:0] p_Result_12_i_fu_358_p3;
wire   [23:0] ap_phi_reg_pp0_iter1_axi_data_V_0_i_reg_205;
wire   [23:0] p_Result_11_i_fu_340_p3;
wire   [23:0] p_Result_i_fu_349_p3;
reg   [23:0] ap_phi_mux_axi_data_V_1_i_phi_fu_219_p6;
wire   [23:0] p_Result_12_1_i_fu_393_p5;
wire   [23:0] ap_phi_reg_pp0_iter1_axi_data_V_1_i_reg_216;
wire   [23:0] p_Result_11_1_i_fu_367_p5;
wire   [23:0] p_Result_1_i_fu_380_p5;
reg   [23:0] ap_phi_mux_axi_data_V_2_i_phi_fu_231_p6;
wire   [23:0] p_Result_12_2_i_fu_432_p5;
wire   [23:0] ap_phi_reg_pp0_iter1_axi_data_V_2_i_reg_227;
wire   [23:0] p_Result_11_2_i_fu_406_p5;
wire   [23:0] p_Result_2_i_fu_419_p5;
reg   [0:0] sof_fu_112;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] zext_ln898_fu_266_p1;
wire   [11:0] zext_ln938_fu_302_p1;
wire   [7:0] trunc_ln145_fu_316_p1;
wire   [7:0] trunc_ln145_8_fu_320_p4;
wire   [7:0] trunc_ln145_9_fu_330_p4;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    m_axis_video_TVALID_int_regslice;
wire    m_axis_video_TREADY_int_regslice;
wire    regslice_both_AXI_video_strm_V_data_V_U_vld_out;
wire    regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk;
wire    regslice_both_AXI_video_strm_V_keep_V_U_ack_in_dummy;
wire    regslice_both_AXI_video_strm_V_keep_V_U_vld_out;
wire    regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk;
wire    regslice_both_AXI_video_strm_V_strb_V_U_ack_in_dummy;
wire    regslice_both_AXI_video_strm_V_strb_V_U_vld_out;
wire    regslice_both_AXI_video_strm_V_user_V_U_apdone_blk;
wire    regslice_both_AXI_video_strm_V_user_V_U_ack_in_dummy;
wire    regslice_both_AXI_video_strm_V_user_V_U_vld_out;
wire    regslice_both_AXI_video_strm_V_last_V_U_apdone_blk;
wire    regslice_both_AXI_video_strm_V_last_V_U_ack_in_dummy;
wire    regslice_both_AXI_video_strm_V_last_V_U_vld_out;
wire    regslice_both_AXI_video_strm_V_id_V_U_apdone_blk;
wire    regslice_both_AXI_video_strm_V_id_V_U_ack_in_dummy;
wire    regslice_both_AXI_video_strm_V_id_V_U_vld_out;
wire    regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk;
wire    regslice_both_AXI_video_strm_V_dest_V_U_ack_in_dummy;
wire    regslice_both_AXI_video_strm_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

bd_0837_vsc_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_245(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(grp_reg_unsigned_short_s_fu_245_d),
    .ap_return(grp_reg_unsigned_short_s_fu_245_ap_return)
);

bd_0837_vsc_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_251(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(Width_dout),
    .ap_return(grp_reg_unsigned_short_s_fu_251_ap_return)
);

bd_0837_vsc_0_regslice_both #(
    .DataWidth( 24 ))
regslice_both_AXI_video_strm_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(ap_phi_mux_axi_data_V_2_i_phi_fu_231_p6),
    .vld_in(m_axis_video_TVALID_int_regslice),
    .ack_in(m_axis_video_TREADY_int_regslice),
    .data_out(m_axis_video_TDATA),
    .vld_out(regslice_both_AXI_video_strm_V_data_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_AXI_video_strm_V_data_V_U_apdone_blk)
);

bd_0837_vsc_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_AXI_video_strm_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(3'd7),
    .vld_in(m_axis_video_TVALID_int_regslice),
    .ack_in(regslice_both_AXI_video_strm_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_video_TKEEP),
    .vld_out(regslice_both_AXI_video_strm_V_keep_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk)
);

bd_0837_vsc_0_regslice_both #(
    .DataWidth( 3 ))
regslice_both_AXI_video_strm_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(3'd0),
    .vld_in(m_axis_video_TVALID_int_regslice),
    .ack_in(regslice_both_AXI_video_strm_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_video_TSTRB),
    .vld_out(regslice_both_AXI_video_strm_V_strb_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk)
);

bd_0837_vsc_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_AXI_video_strm_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(ap_phi_mux_sof_3_phi_fu_196_p4),
    .vld_in(m_axis_video_TVALID_int_regslice),
    .ack_in(regslice_both_AXI_video_strm_V_user_V_U_ack_in_dummy),
    .data_out(m_axis_video_TUSER),
    .vld_out(regslice_both_AXI_video_strm_V_user_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_AXI_video_strm_V_user_V_U_apdone_blk)
);

bd_0837_vsc_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_AXI_video_strm_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(icmp_ln951_reg_503),
    .vld_in(m_axis_video_TVALID_int_regslice),
    .ack_in(regslice_both_AXI_video_strm_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_video_TLAST),
    .vld_out(regslice_both_AXI_video_strm_V_last_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_AXI_video_strm_V_last_V_U_apdone_blk)
);

bd_0837_vsc_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_AXI_video_strm_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(1'd0),
    .vld_in(m_axis_video_TVALID_int_regslice),
    .ack_in(regslice_both_AXI_video_strm_V_id_V_U_ack_in_dummy),
    .data_out(m_axis_video_TID),
    .vld_out(regslice_both_AXI_video_strm_V_id_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_AXI_video_strm_V_id_V_U_apdone_blk)
);

bd_0837_vsc_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_AXI_video_strm_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(1'd0),
    .vld_in(m_axis_video_TVALID_int_regslice),
    .ack_in(regslice_both_AXI_video_strm_V_dest_V_U_ack_in_dummy),
    .data_out(m_axis_video_TDEST),
    .vld_out(regslice_both_AXI_video_strm_V_dest_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd1) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd0) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0) & (cmp19184_i_reg_476 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state5) & (ap_enable_reg_pp0_iter0 == 1'b0)) | ((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd0) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0) & (cmp19184_i_reg_476 == 1'd0)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd0) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0) & (cmp19184_i_reg_476 == 1'd0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_reg_169 <= i_1_reg_480;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_169 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd0) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0) & (cmp19184_i_reg_476 == 1'd0))) begin
        j_reg_180 <= 11'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln938_fu_306_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        j_reg_180 <= j_1_fu_296_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd0) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0) & (cmp19184_i_reg_476 == 1'd0))) begin
        sof_3_reg_191 <= sof_fu_112;
    end else if (((icmp_ln938_reg_499_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sof_3_reg_191 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b0 == ColorMode_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_fu_112 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state7) & (cmp19184_i_reg_476 == 1'd0))) begin
        sof_fu_112 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ColorMode_read_reg_457 <= ColorMode_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp19184_i_reg_476 <= cmp19184_i_fu_276_p2;
        cols_reg_466 <= grp_reg_unsigned_short_s_fu_251_ap_return;
        sub_i_reg_471 <= sub_i_fu_270_p2;
        trunc_ln897_reg_461 <= trunc_ln897_fu_262_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0))) begin
        i_1_reg_480 <= i_1_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln938_reg_499 <= icmp_ln938_fu_306_p2;
        icmp_ln938_reg_499_pp0_iter1_reg <= icmp_ln938_reg_499;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln938_fu_306_p2 == 1'd0))) begin
        icmp_ln951_reg_503 <= icmp_ln951_fu_311_p2;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorMode_blk_n = ColorMode_empty_n;
    end else begin
        ColorMode_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == ColorMode_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ColorMode_read = 1'b1;
    end else begin
        ColorMode_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == ColorMode_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln938_reg_499 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutYUV_blk_n = OutYUV_empty_n;
    end else begin
        OutYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln938_reg_499 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutYUV_read = 1'b1;
    end else begin
        OutYUV_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Width_blk_n = Width_empty_n;
    end else begin
        Width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b0 == ColorMode_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Width_read = 1'b1;
    end else begin
        Width_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln938_fu_306_p2 == 1'd1))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd1) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln938_reg_499 == 1'd0)) begin
        if ((8'd0 == ColorMode_read_reg_457)) begin
            ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6 = p_Result_i_fu_349_p3;
        end else if ((8'd1 == ColorMode_read_reg_457)) begin
            ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6 = p_Result_11_i_fu_340_p3;
        end else if ((~(8'd1 == ColorMode_read_reg_457) & ~(8'd0 == ColorMode_read_reg_457))) begin
            ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6 = p_Result_12_i_fu_358_p3;
        end else begin
            ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6 = ap_phi_reg_pp0_iter1_axi_data_V_0_i_reg_205;
        end
    end else begin
        ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6 = ap_phi_reg_pp0_iter1_axi_data_V_0_i_reg_205;
    end
end

always @ (*) begin
    if ((icmp_ln938_reg_499 == 1'd0)) begin
        if ((8'd0 == ColorMode_read_reg_457)) begin
            ap_phi_mux_axi_data_V_1_i_phi_fu_219_p6 = p_Result_1_i_fu_380_p5;
        end else if ((8'd1 == ColorMode_read_reg_457)) begin
            ap_phi_mux_axi_data_V_1_i_phi_fu_219_p6 = p_Result_11_1_i_fu_367_p5;
        end else if ((~(8'd1 == ColorMode_read_reg_457) & ~(8'd0 == ColorMode_read_reg_457))) begin
            ap_phi_mux_axi_data_V_1_i_phi_fu_219_p6 = p_Result_12_1_i_fu_393_p5;
        end else begin
            ap_phi_mux_axi_data_V_1_i_phi_fu_219_p6 = ap_phi_reg_pp0_iter1_axi_data_V_1_i_reg_216;
        end
    end else begin
        ap_phi_mux_axi_data_V_1_i_phi_fu_219_p6 = ap_phi_reg_pp0_iter1_axi_data_V_1_i_reg_216;
    end
end

always @ (*) begin
    if ((icmp_ln938_reg_499 == 1'd0)) begin
        if ((8'd0 == ColorMode_read_reg_457)) begin
            ap_phi_mux_axi_data_V_2_i_phi_fu_231_p6 = p_Result_2_i_fu_419_p5;
        end else if ((8'd1 == ColorMode_read_reg_457)) begin
            ap_phi_mux_axi_data_V_2_i_phi_fu_231_p6 = p_Result_11_2_i_fu_406_p5;
        end else if ((~(8'd1 == ColorMode_read_reg_457) & ~(8'd0 == ColorMode_read_reg_457))) begin
            ap_phi_mux_axi_data_V_2_i_phi_fu_231_p6 = p_Result_12_2_i_fu_432_p5;
        end else begin
            ap_phi_mux_axi_data_V_2_i_phi_fu_231_p6 = ap_phi_reg_pp0_iter1_axi_data_V_2_i_reg_227;
        end
    end else begin
        ap_phi_mux_axi_data_V_2_i_phi_fu_231_p6 = ap_phi_reg_pp0_iter1_axi_data_V_2_i_reg_227;
    end
end

always @ (*) begin
    if (((icmp_ln938_reg_499_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_sof_3_phi_fu_196_p4 = 1'd0;
    end else begin
        ap_phi_mux_sof_3_phi_fu_196_p4 = sof_3_reg_191;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd1) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln938_reg_499_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0)) | ((icmp_ln938_reg_499 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        m_axis_video_TDATA_blk_n = m_axis_video_TREADY_int_regslice;
    end else begin
        m_axis_video_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln938_reg_499 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axis_video_TVALID_int_regslice = 1'b1;
    end else begin
        m_axis_video_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((1'b0 == ColorMode_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd1) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd0) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0) & (cmp19184_i_reg_476 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln936_fu_291_p2 == 1'd0) & (regslice_both_AXI_video_strm_V_data_V_U_apdone_blk == 1'b0) & (cmp19184_i_reg_476 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln938_reg_499_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (m_axis_video_TREADY_int_regslice == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln938_reg_499 == 1'd0) & (m_axis_video_TREADY_int_regslice == 1'b0)) | ((icmp_ln938_reg_499 == 1'd0) & (1'b0 == OutYUV_empty_n)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state6_io) | ((icmp_ln938_reg_499_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state5_io) | ((icmp_ln938_reg_499 == 1'd0) & (m_axis_video_TREADY_int_regslice == 1'b0)) | ((icmp_ln938_reg_499 == 1'd0) & (1'b0 == OutYUV_empty_n)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((1'b1 == ap_block_state6_io) | ((icmp_ln938_reg_499_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state5_io) | ((icmp_ln938_reg_499 == 1'd0) & (m_axis_video_TREADY_int_regslice == 1'b0)) | ((icmp_ln938_reg_499 == 1'd0) & (1'b0 == OutYUV_empty_n)))));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == ColorMode_empty_n) | (1'b0 == Width_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((icmp_ln938_reg_499 == 1'd0) & (m_axis_video_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (((icmp_ln938_reg_499 == 1'd0) & (m_axis_video_TREADY_int_regslice == 1'b0)) | ((icmp_ln938_reg_499 == 1'd0) & (1'b0 == OutYUV_empty_n)));
end

always @ (*) begin
    ap_block_state6_io = ((icmp_ln938_reg_499_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = ((icmp_ln938_reg_499_pp0_iter1_reg == 1'd0) & (m_axis_video_TREADY_int_regslice == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter1_axi_data_V_0_i_reg_205 = 'bx;

assign ap_phi_reg_pp0_iter1_axi_data_V_1_i_reg_216 = 'bx;

assign ap_phi_reg_pp0_iter1_axi_data_V_2_i_reg_227 = 'bx;

assign cmp19184_i_fu_276_p2 = ((grp_reg_unsigned_short_s_fu_251_ap_return == 11'd0) ? 1'b1 : 1'b0);

assign grp_reg_unsigned_short_s_fu_245_d = Height_dout;

assign i_1_fu_282_p2 = (i_reg_169 + 10'd1);

assign icmp_ln936_fu_291_p2 = ((i_reg_169 == trunc_ln897_reg_461) ? 1'b1 : 1'b0);

assign icmp_ln938_fu_306_p2 = ((j_reg_180 == cols_reg_466) ? 1'b1 : 1'b0);

assign icmp_ln951_fu_311_p2 = ((zext_ln938_fu_302_p1 == sub_i_reg_471) ? 1'b1 : 1'b0);

assign j_1_fu_296_p2 = (j_reg_180 + 11'd1);

assign m_axis_video_TVALID = regslice_both_AXI_video_strm_V_data_V_U_vld_out;

assign p_Result_11_1_i_fu_367_p5 = {{ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6[23:16]}, {trunc_ln145_8_fu_320_p4}, {ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6[7:0]}};

assign p_Result_11_2_i_fu_406_p5 = {{trunc_ln145_9_fu_330_p4}, {ap_phi_mux_axi_data_V_1_i_phi_fu_219_p6[15:0]}};

assign p_Result_11_i_fu_340_p3 = {{16'd65535}, {trunc_ln145_fu_316_p1}};

assign p_Result_12_1_i_fu_393_p5 = {{ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6[23:16]}, {trunc_ln145_8_fu_320_p4}, {ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6[7:0]}};

assign p_Result_12_2_i_fu_432_p5 = {{trunc_ln145_9_fu_330_p4}, {ap_phi_mux_axi_data_V_1_i_phi_fu_219_p6[15:0]}};

assign p_Result_12_i_fu_358_p3 = {{16'd65535}, {trunc_ln145_fu_316_p1}};

assign p_Result_1_i_fu_380_p5 = {{ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6[23:16]}, {trunc_ln145_9_fu_330_p4}, {ap_phi_mux_axi_data_V_0_i_phi_fu_208_p6[7:0]}};

assign p_Result_2_i_fu_419_p5 = {{trunc_ln145_fu_316_p1}, {ap_phi_mux_axi_data_V_1_i_phi_fu_219_p6[15:0]}};

assign p_Result_i_fu_349_p3 = {{16'd65535}, {trunc_ln145_8_fu_320_p4}};

assign sub_i_fu_270_p2 = ($signed(zext_ln898_fu_266_p1) + $signed(12'd4095));

assign trunc_ln145_8_fu_320_p4 = {{OutYUV_dout[15:8]}};

assign trunc_ln145_9_fu_330_p4 = {{OutYUV_dout[23:16]}};

assign trunc_ln145_fu_316_p1 = OutYUV_dout[7:0];

assign trunc_ln897_fu_262_p1 = grp_reg_unsigned_short_s_fu_245_ap_return[9:0];

assign zext_ln898_fu_266_p1 = grp_reg_unsigned_short_s_fu_251_ap_return;

assign zext_ln938_fu_302_p1 = j_reg_180;

endmodule //bd_0837_vsc_0_MultiPixStream2AXIvideo
