# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Travail/s4InfoAtelier4/s4InfoAtelier4.srcs/sources_1/bd/atelier4/ip/atelier4_processing_system7_0_0/atelier4_processing_system7_0_0.xci
# IP: The module: 'atelier4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_processing_system7_0_0/atelier4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'atelier4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Travail/s4InfoAtelier4/s4InfoAtelier4.srcs/sources_1/bd/atelier4/ip/atelier4_processing_system7_0_0/atelier4_processing_system7_0_0.xci
# IP: The module: 'atelier4_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_processing_system7_0_0/atelier4_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'atelier4_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
