// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bd_0837_hsc_0_hscale_polyphase (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        FiltCoeff_address0,
        FiltCoeff_ce0,
        FiltCoeff_q0,
        FiltCoeff1_address0,
        FiltCoeff1_ce0,
        FiltCoeff1_q0,
        FiltCoeff2_address0,
        FiltCoeff2_ce0,
        FiltCoeff2_q0,
        FiltCoeff3_address0,
        FiltCoeff3_ce0,
        FiltCoeff3_q0,
        FiltCoeff4_address0,
        FiltCoeff4_ce0,
        FiltCoeff4_q0,
        FiltCoeff5_address0,
        FiltCoeff5_ce0,
        FiltCoeff5_q0,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        PhasesH_0_read,
        p_read124,
        ap_return_0,
        ap_return_1,
        ap_return_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
output  [5:0] FiltCoeff_address0;
output   FiltCoeff_ce0;
input  [15:0] FiltCoeff_q0;
output  [5:0] FiltCoeff1_address0;
output   FiltCoeff1_ce0;
input  [15:0] FiltCoeff1_q0;
output  [5:0] FiltCoeff2_address0;
output   FiltCoeff2_ce0;
input  [15:0] FiltCoeff2_q0;
output  [5:0] FiltCoeff3_address0;
output   FiltCoeff3_ce0;
input  [15:0] FiltCoeff3_q0;
output  [5:0] FiltCoeff4_address0;
output   FiltCoeff4_ce0;
input  [15:0] FiltCoeff4_q0;
output  [5:0] FiltCoeff5_address0;
output   FiltCoeff5_ce0;
input  [15:0] FiltCoeff5_q0;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;
input  [7:0] p_read9;
input  [7:0] p_read10;
input  [7:0] p_read11;
input  [7:0] p_read12;
input  [7:0] p_read13;
input  [7:0] p_read14;
input  [7:0] p_read15;
input  [7:0] p_read16;
input  [7:0] p_read17;
input  [7:0] p_read18;
input  [7:0] p_read19;
input  [7:0] p_read20;
input  [7:0] p_read21;
input  [7:0] p_read22;
input  [7:0] p_read23;
input  [5:0] PhasesH_0_read;
input  [1:0] p_read124;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg FiltCoeff_ce0;
reg FiltCoeff1_ce0;
reg FiltCoeff2_ce0;
reg FiltCoeff3_ce0;
reg FiltCoeff4_ce0;
reg FiltCoeff5_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] idxprom5_fu_356_p1;
reg   [63:0] idxprom5_reg_1279;
reg   [63:0] idxprom5_reg_1279_pp0_iter1_reg;
reg   [63:0] idxprom5_reg_1279_pp0_iter2_reg;
reg   [63:0] idxprom5_reg_1279_pp0_iter3_reg;
reg   [63:0] idxprom5_reg_1279_pp0_iter4_reg;
wire   [7:0] tmp_fu_367_p10;
reg   [7:0] tmp_reg_1293;
wire   [7:0] select_ln215_3_fu_455_p3;
reg   [7:0] select_ln215_3_reg_1298;
reg   [7:0] select_ln215_3_reg_1298_pp0_iter1_reg;
wire   [7:0] select_ln215_7_fu_487_p3;
reg   [7:0] select_ln215_7_reg_1303;
reg   [7:0] select_ln215_7_reg_1303_pp0_iter1_reg;
reg   [7:0] select_ln215_7_reg_1303_pp0_iter2_reg;
wire   [7:0] select_ln215_10_fu_517_p3;
reg   [7:0] select_ln215_10_reg_1308;
reg   [7:0] select_ln215_10_reg_1308_pp0_iter1_reg;
reg   [7:0] select_ln215_10_reg_1308_pp0_iter2_reg;
reg   [7:0] select_ln215_10_reg_1308_pp0_iter3_reg;
wire   [7:0] select_ln215_12_fu_533_p3;
reg   [7:0] select_ln215_12_reg_1313;
reg   [7:0] select_ln215_12_reg_1313_pp0_iter1_reg;
reg   [7:0] select_ln215_12_reg_1313_pp0_iter2_reg;
reg   [7:0] select_ln215_12_reg_1313_pp0_iter3_reg;
reg   [7:0] select_ln215_12_reg_1313_pp0_iter4_reg;
wire   [7:0] select_ln215_13_fu_541_p3;
reg   [7:0] select_ln215_13_reg_1318;
reg   [7:0] select_ln215_13_reg_1318_pp0_iter1_reg;
reg   [7:0] select_ln215_13_reg_1318_pp0_iter2_reg;
reg   [7:0] select_ln215_13_reg_1318_pp0_iter3_reg;
reg   [7:0] select_ln215_13_reg_1318_pp0_iter4_reg;
reg   [7:0] select_ln215_13_reg_1318_pp0_iter5_reg;
wire   [7:0] tmp_1_fu_549_p10;
reg   [7:0] tmp_1_reg_1323;
wire   [7:0] select_ln215_17_fu_595_p3;
reg   [7:0] select_ln215_17_reg_1328;
reg   [7:0] select_ln215_17_reg_1328_pp0_iter1_reg;
wire   [7:0] select_ln215_21_fu_627_p3;
reg   [7:0] select_ln215_21_reg_1333;
reg   [7:0] select_ln215_21_reg_1333_pp0_iter1_reg;
reg   [7:0] select_ln215_21_reg_1333_pp0_iter2_reg;
wire   [7:0] select_ln215_24_fu_651_p3;
reg   [7:0] select_ln215_24_reg_1338;
reg   [7:0] select_ln215_24_reg_1338_pp0_iter1_reg;
reg   [7:0] select_ln215_24_reg_1338_pp0_iter2_reg;
reg   [7:0] select_ln215_24_reg_1338_pp0_iter3_reg;
wire   [7:0] select_ln215_26_fu_667_p3;
reg   [7:0] select_ln215_26_reg_1343;
reg   [7:0] select_ln215_26_reg_1343_pp0_iter1_reg;
reg   [7:0] select_ln215_26_reg_1343_pp0_iter2_reg;
reg   [7:0] select_ln215_26_reg_1343_pp0_iter3_reg;
reg   [7:0] select_ln215_26_reg_1343_pp0_iter4_reg;
wire   [7:0] select_ln215_27_fu_675_p3;
reg   [7:0] select_ln215_27_reg_1348;
reg   [7:0] select_ln215_27_reg_1348_pp0_iter1_reg;
reg   [7:0] select_ln215_27_reg_1348_pp0_iter2_reg;
reg   [7:0] select_ln215_27_reg_1348_pp0_iter3_reg;
reg   [7:0] select_ln215_27_reg_1348_pp0_iter4_reg;
reg   [7:0] select_ln215_27_reg_1348_pp0_iter5_reg;
wire   [7:0] tmp_2_fu_683_p10;
reg   [7:0] tmp_2_reg_1353;
wire   [7:0] select_ln215_31_fu_729_p3;
reg   [7:0] select_ln215_31_reg_1358;
reg   [7:0] select_ln215_31_reg_1358_pp0_iter1_reg;
wire   [7:0] select_ln215_35_fu_761_p3;
reg   [7:0] select_ln215_35_reg_1363;
reg   [7:0] select_ln215_35_reg_1363_pp0_iter1_reg;
reg   [7:0] select_ln215_35_reg_1363_pp0_iter2_reg;
wire   [7:0] select_ln215_38_fu_785_p3;
reg   [7:0] select_ln215_38_reg_1368;
reg   [7:0] select_ln215_38_reg_1368_pp0_iter1_reg;
reg   [7:0] select_ln215_38_reg_1368_pp0_iter2_reg;
reg   [7:0] select_ln215_38_reg_1368_pp0_iter3_reg;
wire   [7:0] select_ln215_40_fu_801_p3;
reg   [7:0] select_ln215_40_reg_1373;
reg   [7:0] select_ln215_40_reg_1373_pp0_iter1_reg;
reg   [7:0] select_ln215_40_reg_1373_pp0_iter2_reg;
reg   [7:0] select_ln215_40_reg_1373_pp0_iter3_reg;
reg   [7:0] select_ln215_40_reg_1373_pp0_iter4_reg;
wire   [7:0] select_ln215_41_fu_809_p3;
reg   [7:0] select_ln215_41_reg_1378;
reg   [7:0] select_ln215_41_reg_1378_pp0_iter1_reg;
reg   [7:0] select_ln215_41_reg_1378_pp0_iter2_reg;
reg   [7:0] select_ln215_41_reg_1378_pp0_iter3_reg;
reg   [7:0] select_ln215_41_reg_1378_pp0_iter4_reg;
reg   [7:0] select_ln215_41_reg_1378_pp0_iter5_reg;
wire  signed [23:0] sext_ln215_fu_820_p1;
wire  signed [23:0] sext_ln215_1_fu_833_p1;
wire  signed [23:0] sext_ln215_2_fu_846_p1;
wire  signed [23:0] sext_ln215_3_fu_862_p1;
wire  signed [23:0] sext_ln215_4_fu_884_p1;
wire  signed [25:0] grp_fu_1171_p3;
wire  signed [23:0] sext_ln215_5_fu_903_p1;
wire  signed [25:0] grp_fu_1179_p3;
wire  signed [25:0] grp_fu_1187_p3;
wire  signed [26:0] grp_fu_1222_p3;
wire  signed [26:0] grp_fu_1230_p3;
wire  signed [26:0] grp_fu_1238_p3;
reg    ap_block_pp0_stage0_subdone;
wire   [2:0] p_read1_cast_fu_352_p1;
wire   [2:0] idx_fu_361_p2;
wire   [0:0] icmp_ln215_3_fu_407_p2;
wire   [0:0] icmp_ln215_2_fu_401_p2;
wire   [0:0] icmp_ln215_1_fu_395_p2;
wire   [0:0] icmp_ln215_fu_389_p2;
wire   [0:0] or_ln215_fu_421_p2;
wire   [7:0] select_ln215_fu_413_p3;
wire   [7:0] select_ln215_1_fu_427_p3;
wire   [0:0] or_ln215_1_fu_435_p2;
wire   [0:0] or_ln215_2_fu_449_p2;
wire   [7:0] select_ln215_2_fu_441_p3;
wire   [7:0] select_ln215_4_fu_463_p3;
wire   [7:0] select_ln215_5_fu_471_p3;
wire   [7:0] select_ln215_6_fu_479_p3;
wire   [0:0] or_ln215_3_fu_503_p2;
wire   [7:0] select_ln215_8_fu_495_p3;
wire   [7:0] select_ln215_9_fu_509_p3;
wire   [7:0] select_ln215_11_fu_525_p3;
wire   [7:0] select_ln215_14_fu_571_p3;
wire   [7:0] select_ln215_15_fu_579_p3;
wire   [7:0] select_ln215_16_fu_587_p3;
wire   [7:0] select_ln215_18_fu_603_p3;
wire   [7:0] select_ln215_19_fu_611_p3;
wire   [7:0] select_ln215_20_fu_619_p3;
wire   [7:0] select_ln215_22_fu_635_p3;
wire   [7:0] select_ln215_23_fu_643_p3;
wire   [7:0] select_ln215_25_fu_659_p3;
wire   [7:0] select_ln215_28_fu_705_p3;
wire   [7:0] select_ln215_29_fu_713_p3;
wire   [7:0] select_ln215_30_fu_721_p3;
wire   [7:0] select_ln215_32_fu_737_p3;
wire   [7:0] select_ln215_33_fu_745_p3;
wire   [7:0] select_ln215_34_fu_753_p3;
wire   [7:0] select_ln215_36_fu_769_p3;
wire   [7:0] select_ln215_37_fu_777_p3;
wire   [7:0] select_ln215_39_fu_793_p3;
wire  signed [23:0] grp_fu_1117_p3;
wire  signed [23:0] grp_fu_1126_p3;
wire  signed [23:0] grp_fu_1135_p3;
wire  signed [24:0] grp_fu_1144_p3;
wire  signed [24:0] grp_fu_1153_p3;
wire  signed [24:0] grp_fu_1162_p3;
wire  signed [25:0] grp_fu_1195_p3;
wire  signed [25:0] grp_fu_1204_p3;
wire  signed [25:0] grp_fu_1213_p3;
wire  signed [26:0] grp_fu_1246_p3;
wire   [6:0] tmp_4_fu_929_p4;
wire   [0:0] tmp_3_fu_922_p3;
wire   [0:0] xor_ln301_fu_953_p2;
wire   [0:0] icmp_ln861_fu_938_p2;
wire   [0:0] or_ln301_fu_967_p2;
wire   [7:0] select_ln301_3_fu_959_p3;
wire   [7:0] trunc_ln3_fu_944_p4;
wire  signed [26:0] grp_fu_1257_p3;
wire   [6:0] tmp_6_fu_988_p4;
wire   [0:0] tmp_5_fu_981_p3;
wire   [0:0] xor_ln301_1_fu_1012_p2;
wire   [0:0] icmp_ln861_1_fu_997_p2;
wire   [0:0] or_ln301_1_fu_1026_p2;
wire   [7:0] select_ln301_4_fu_1018_p3;
wire   [7:0] trunc_ln301_1_fu_1003_p4;
wire  signed [26:0] grp_fu_1268_p3;
wire   [6:0] tmp_8_fu_1047_p4;
wire   [0:0] tmp_7_fu_1040_p3;
wire   [0:0] xor_ln301_2_fu_1071_p2;
wire   [0:0] icmp_ln861_2_fu_1056_p2;
wire   [0:0] or_ln301_2_fu_1085_p2;
wire   [7:0] select_ln301_5_fu_1077_p3;
wire   [7:0] trunc_ln301_2_fu_1062_p4;
wire   [7:0] select_ln301_fu_973_p3;
wire   [7:0] select_ln301_1_fu_1032_p3;
wire   [7:0] select_ln301_2_fu_1091_p3;
wire   [7:0] grp_fu_1117_p0;
wire  signed [15:0] grp_fu_1117_p1;
wire   [12:0] grp_fu_1117_p2;
wire   [7:0] grp_fu_1126_p0;
wire  signed [15:0] grp_fu_1126_p1;
wire   [12:0] grp_fu_1126_p2;
wire   [7:0] grp_fu_1135_p0;
wire  signed [15:0] grp_fu_1135_p1;
wire   [12:0] grp_fu_1135_p2;
wire   [7:0] grp_fu_1144_p0;
wire  signed [15:0] grp_fu_1144_p1;
wire   [7:0] grp_fu_1153_p0;
wire  signed [15:0] grp_fu_1153_p1;
wire   [7:0] grp_fu_1162_p0;
wire  signed [15:0] grp_fu_1162_p1;
wire   [7:0] grp_fu_1171_p0;
wire  signed [15:0] grp_fu_1171_p1;
wire   [7:0] grp_fu_1179_p0;
wire  signed [15:0] grp_fu_1179_p1;
wire   [7:0] grp_fu_1187_p0;
wire  signed [15:0] grp_fu_1187_p1;
wire   [7:0] grp_fu_1195_p0;
wire  signed [15:0] grp_fu_1195_p1;
wire   [7:0] grp_fu_1204_p0;
wire  signed [15:0] grp_fu_1204_p1;
wire   [7:0] grp_fu_1213_p0;
wire  signed [15:0] grp_fu_1213_p1;
wire   [7:0] grp_fu_1222_p0;
wire  signed [15:0] grp_fu_1222_p1;
wire   [7:0] grp_fu_1230_p0;
wire  signed [15:0] grp_fu_1230_p1;
wire   [7:0] grp_fu_1238_p0;
wire  signed [15:0] grp_fu_1238_p1;
wire   [7:0] grp_fu_1246_p0;
wire  signed [15:0] grp_fu_1246_p1;
wire   [7:0] grp_fu_1257_p0;
wire  signed [15:0] grp_fu_1257_p1;
wire   [7:0] grp_fu_1268_p0;
wire  signed [15:0] grp_fu_1268_p1;
reg    grp_fu_1117_ce;
reg    grp_fu_1126_ce;
reg    grp_fu_1135_ce;
reg    grp_fu_1144_ce;
reg    grp_fu_1153_ce;
reg    grp_fu_1162_ce;
reg    grp_fu_1171_ce;
reg    grp_fu_1179_ce;
reg    grp_fu_1187_ce;
reg    grp_fu_1195_ce;
reg    grp_fu_1204_ce;
reg    grp_fu_1213_ce;
reg    grp_fu_1222_ce;
reg    grp_fu_1230_ce;
reg    grp_fu_1238_ce;
reg    grp_fu_1246_ce;
reg    grp_fu_1257_ce;
reg    grp_fu_1268_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to8;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [23:0] grp_fu_1117_p00;
wire   [23:0] grp_fu_1126_p00;
wire   [23:0] grp_fu_1135_p00;
wire   [23:0] grp_fu_1144_p00;
wire   [23:0] grp_fu_1153_p00;
wire   [23:0] grp_fu_1162_p00;
wire   [23:0] grp_fu_1171_p00;
wire   [23:0] grp_fu_1179_p00;
wire   [23:0] grp_fu_1187_p00;
wire   [23:0] grp_fu_1195_p00;
wire   [23:0] grp_fu_1204_p00;
wire   [23:0] grp_fu_1213_p00;
wire   [23:0] grp_fu_1222_p00;
wire   [23:0] grp_fu_1230_p00;
wire   [23:0] grp_fu_1238_p00;
wire   [23:0] grp_fu_1246_p00;
wire   [23:0] grp_fu_1257_p00;
wire   [23:0] grp_fu_1268_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
end

bd_0837_hsc_0_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U34(
    .din0(p_read),
    .din1(p_read3),
    .din2(p_read6),
    .din3(p_read9),
    .din4(p_read12),
    .din5(p_read15),
    .din6(p_read18),
    .din7(p_read21),
    .din8(idx_fu_361_p2),
    .dout(tmp_fu_367_p10)
);

bd_0837_hsc_0_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U35(
    .din0(p_read1),
    .din1(p_read4),
    .din2(p_read7),
    .din3(p_read10),
    .din4(p_read13),
    .din5(p_read16),
    .din6(p_read19),
    .din7(p_read22),
    .din8(idx_fu_361_p2),
    .dout(tmp_1_fu_549_p10)
);

bd_0837_hsc_0_mux_83_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_83_8_1_1_U36(
    .din0(p_read2),
    .din1(p_read5),
    .din2(p_read8),
    .din3(p_read11),
    .din4(p_read14),
    .din5(p_read17),
    .din6(p_read20),
    .din7(p_read23),
    .din8(idx_fu_361_p2),
    .dout(tmp_2_fu_683_p10)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_13ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 24 ))
mac_muladd_8ns_16s_13ns_24_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1117_p0),
    .din1(grp_fu_1117_p1),
    .din2(grp_fu_1117_p2),
    .ce(grp_fu_1117_ce),
    .dout(grp_fu_1117_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_13ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 24 ))
mac_muladd_8ns_16s_13ns_24_4_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1126_p0),
    .din1(grp_fu_1126_p1),
    .din2(grp_fu_1126_p2),
    .ce(grp_fu_1126_ce),
    .dout(grp_fu_1126_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_13ns_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 24 ))
mac_muladd_8ns_16s_13ns_24_4_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1135_p0),
    .din1(grp_fu_1135_p1),
    .din2(grp_fu_1135_p2),
    .ce(grp_fu_1135_ce),
    .dout(grp_fu_1135_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_24s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_8ns_16s_24s_25_4_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1144_p0),
    .din1(grp_fu_1144_p1),
    .din2(grp_fu_1117_p3),
    .ce(grp_fu_1144_ce),
    .dout(grp_fu_1144_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_24s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_8ns_16s_24s_25_4_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1153_p0),
    .din1(grp_fu_1153_p1),
    .din2(grp_fu_1126_p3),
    .ce(grp_fu_1153_ce),
    .dout(grp_fu_1153_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_24s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
mac_muladd_8ns_16s_24s_25_4_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1162_p0),
    .din1(grp_fu_1162_p1),
    .din2(grp_fu_1135_p3),
    .ce(grp_fu_1162_ce),
    .dout(grp_fu_1162_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_25s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 26 ))
mac_muladd_8ns_16s_25s_26_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1171_p0),
    .din1(grp_fu_1171_p1),
    .din2(grp_fu_1144_p3),
    .ce(grp_fu_1171_ce),
    .dout(grp_fu_1171_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_25s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 26 ))
mac_muladd_8ns_16s_25s_26_4_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1179_p0),
    .din1(grp_fu_1179_p1),
    .din2(grp_fu_1153_p3),
    .ce(grp_fu_1179_ce),
    .dout(grp_fu_1179_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_25s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 26 ))
mac_muladd_8ns_16s_25s_26_4_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1187_p0),
    .din1(grp_fu_1187_p1),
    .din2(grp_fu_1162_p3),
    .ce(grp_fu_1187_ce),
    .dout(grp_fu_1187_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_8ns_16s_26s_26_4_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1195_p0),
    .din1(grp_fu_1195_p1),
    .din2(grp_fu_1171_p3),
    .ce(grp_fu_1195_ce),
    .dout(grp_fu_1195_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_8ns_16s_26s_26_4_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1204_p0),
    .din1(grp_fu_1204_p1),
    .din2(grp_fu_1179_p3),
    .ce(grp_fu_1204_ce),
    .dout(grp_fu_1204_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mac_muladd_8ns_16s_26s_26_4_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1213_p0),
    .din1(grp_fu_1213_p1),
    .din2(grp_fu_1187_p3),
    .ce(grp_fu_1213_ce),
    .dout(grp_fu_1213_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_26s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
mac_muladd_8ns_16s_26s_27_4_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1222_p0),
    .din1(grp_fu_1222_p1),
    .din2(grp_fu_1195_p3),
    .ce(grp_fu_1222_ce),
    .dout(grp_fu_1222_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_26s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
mac_muladd_8ns_16s_26s_27_4_1_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1230_p0),
    .din1(grp_fu_1230_p1),
    .din2(grp_fu_1204_p3),
    .ce(grp_fu_1230_ce),
    .dout(grp_fu_1230_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_26s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
mac_muladd_8ns_16s_26s_27_4_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1238_p0),
    .din1(grp_fu_1238_p1),
    .din2(grp_fu_1213_p3),
    .ce(grp_fu_1238_ce),
    .dout(grp_fu_1238_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
mac_muladd_8ns_16s_27s_27_4_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1246_p0),
    .din1(grp_fu_1246_p1),
    .din2(grp_fu_1222_p3),
    .ce(grp_fu_1246_ce),
    .dout(grp_fu_1246_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
mac_muladd_8ns_16s_27s_27_4_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1257_p0),
    .din1(grp_fu_1257_p1),
    .din2(grp_fu_1230_p3),
    .ce(grp_fu_1257_ce),
    .dout(grp_fu_1257_p3)
);

bd_0837_hsc_0_mac_muladd_8ns_16s_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
mac_muladd_8ns_16s_27s_27_4_1_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1268_p0),
    .din1(grp_fu_1268_p1),
    .din2(grp_fu_1238_p3),
    .ce(grp_fu_1268_ce),
    .dout(grp_fu_1268_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        idxprom5_reg_1279[5 : 0] <= idxprom5_fu_356_p1[5 : 0];
        idxprom5_reg_1279_pp0_iter1_reg[5 : 0] <= idxprom5_reg_1279[5 : 0];
        select_ln215_10_reg_1308 <= select_ln215_10_fu_517_p3;
        select_ln215_10_reg_1308_pp0_iter1_reg <= select_ln215_10_reg_1308;
        select_ln215_12_reg_1313 <= select_ln215_12_fu_533_p3;
        select_ln215_12_reg_1313_pp0_iter1_reg <= select_ln215_12_reg_1313;
        select_ln215_13_reg_1318 <= select_ln215_13_fu_541_p3;
        select_ln215_13_reg_1318_pp0_iter1_reg <= select_ln215_13_reg_1318;
        select_ln215_17_reg_1328 <= select_ln215_17_fu_595_p3;
        select_ln215_17_reg_1328_pp0_iter1_reg <= select_ln215_17_reg_1328;
        select_ln215_21_reg_1333 <= select_ln215_21_fu_627_p3;
        select_ln215_21_reg_1333_pp0_iter1_reg <= select_ln215_21_reg_1333;
        select_ln215_24_reg_1338 <= select_ln215_24_fu_651_p3;
        select_ln215_24_reg_1338_pp0_iter1_reg <= select_ln215_24_reg_1338;
        select_ln215_26_reg_1343 <= select_ln215_26_fu_667_p3;
        select_ln215_26_reg_1343_pp0_iter1_reg <= select_ln215_26_reg_1343;
        select_ln215_27_reg_1348 <= select_ln215_27_fu_675_p3;
        select_ln215_27_reg_1348_pp0_iter1_reg <= select_ln215_27_reg_1348;
        select_ln215_31_reg_1358 <= select_ln215_31_fu_729_p3;
        select_ln215_31_reg_1358_pp0_iter1_reg <= select_ln215_31_reg_1358;
        select_ln215_35_reg_1363 <= select_ln215_35_fu_761_p3;
        select_ln215_35_reg_1363_pp0_iter1_reg <= select_ln215_35_reg_1363;
        select_ln215_38_reg_1368 <= select_ln215_38_fu_785_p3;
        select_ln215_38_reg_1368_pp0_iter1_reg <= select_ln215_38_reg_1368;
        select_ln215_3_reg_1298 <= select_ln215_3_fu_455_p3;
        select_ln215_3_reg_1298_pp0_iter1_reg <= select_ln215_3_reg_1298;
        select_ln215_40_reg_1373 <= select_ln215_40_fu_801_p3;
        select_ln215_40_reg_1373_pp0_iter1_reg <= select_ln215_40_reg_1373;
        select_ln215_41_reg_1378 <= select_ln215_41_fu_809_p3;
        select_ln215_41_reg_1378_pp0_iter1_reg <= select_ln215_41_reg_1378;
        select_ln215_7_reg_1303 <= select_ln215_7_fu_487_p3;
        select_ln215_7_reg_1303_pp0_iter1_reg <= select_ln215_7_reg_1303;
        tmp_1_reg_1323 <= tmp_1_fu_549_p10;
        tmp_2_reg_1353 <= tmp_2_fu_683_p10;
        tmp_reg_1293 <= tmp_fu_367_p10;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        idxprom5_reg_1279_pp0_iter2_reg[5 : 0] <= idxprom5_reg_1279_pp0_iter1_reg[5 : 0];
        idxprom5_reg_1279_pp0_iter3_reg[5 : 0] <= idxprom5_reg_1279_pp0_iter2_reg[5 : 0];
        idxprom5_reg_1279_pp0_iter4_reg[5 : 0] <= idxprom5_reg_1279_pp0_iter3_reg[5 : 0];
        select_ln215_10_reg_1308_pp0_iter2_reg <= select_ln215_10_reg_1308_pp0_iter1_reg;
        select_ln215_10_reg_1308_pp0_iter3_reg <= select_ln215_10_reg_1308_pp0_iter2_reg;
        select_ln215_12_reg_1313_pp0_iter2_reg <= select_ln215_12_reg_1313_pp0_iter1_reg;
        select_ln215_12_reg_1313_pp0_iter3_reg <= select_ln215_12_reg_1313_pp0_iter2_reg;
        select_ln215_12_reg_1313_pp0_iter4_reg <= select_ln215_12_reg_1313_pp0_iter3_reg;
        select_ln215_13_reg_1318_pp0_iter2_reg <= select_ln215_13_reg_1318_pp0_iter1_reg;
        select_ln215_13_reg_1318_pp0_iter3_reg <= select_ln215_13_reg_1318_pp0_iter2_reg;
        select_ln215_13_reg_1318_pp0_iter4_reg <= select_ln215_13_reg_1318_pp0_iter3_reg;
        select_ln215_13_reg_1318_pp0_iter5_reg <= select_ln215_13_reg_1318_pp0_iter4_reg;
        select_ln215_21_reg_1333_pp0_iter2_reg <= select_ln215_21_reg_1333_pp0_iter1_reg;
        select_ln215_24_reg_1338_pp0_iter2_reg <= select_ln215_24_reg_1338_pp0_iter1_reg;
        select_ln215_24_reg_1338_pp0_iter3_reg <= select_ln215_24_reg_1338_pp0_iter2_reg;
        select_ln215_26_reg_1343_pp0_iter2_reg <= select_ln215_26_reg_1343_pp0_iter1_reg;
        select_ln215_26_reg_1343_pp0_iter3_reg <= select_ln215_26_reg_1343_pp0_iter2_reg;
        select_ln215_26_reg_1343_pp0_iter4_reg <= select_ln215_26_reg_1343_pp0_iter3_reg;
        select_ln215_27_reg_1348_pp0_iter2_reg <= select_ln215_27_reg_1348_pp0_iter1_reg;
        select_ln215_27_reg_1348_pp0_iter3_reg <= select_ln215_27_reg_1348_pp0_iter2_reg;
        select_ln215_27_reg_1348_pp0_iter4_reg <= select_ln215_27_reg_1348_pp0_iter3_reg;
        select_ln215_27_reg_1348_pp0_iter5_reg <= select_ln215_27_reg_1348_pp0_iter4_reg;
        select_ln215_35_reg_1363_pp0_iter2_reg <= select_ln215_35_reg_1363_pp0_iter1_reg;
        select_ln215_38_reg_1368_pp0_iter2_reg <= select_ln215_38_reg_1368_pp0_iter1_reg;
        select_ln215_38_reg_1368_pp0_iter3_reg <= select_ln215_38_reg_1368_pp0_iter2_reg;
        select_ln215_40_reg_1373_pp0_iter2_reg <= select_ln215_40_reg_1373_pp0_iter1_reg;
        select_ln215_40_reg_1373_pp0_iter3_reg <= select_ln215_40_reg_1373_pp0_iter2_reg;
        select_ln215_40_reg_1373_pp0_iter4_reg <= select_ln215_40_reg_1373_pp0_iter3_reg;
        select_ln215_41_reg_1378_pp0_iter2_reg <= select_ln215_41_reg_1378_pp0_iter1_reg;
        select_ln215_41_reg_1378_pp0_iter3_reg <= select_ln215_41_reg_1378_pp0_iter2_reg;
        select_ln215_41_reg_1378_pp0_iter4_reg <= select_ln215_41_reg_1378_pp0_iter3_reg;
        select_ln215_41_reg_1378_pp0_iter5_reg <= select_ln215_41_reg_1378_pp0_iter4_reg;
        select_ln215_7_reg_1303_pp0_iter2_reg <= select_ln215_7_reg_1303_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        FiltCoeff1_ce0 = 1'b1;
    end else begin
        FiltCoeff1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        FiltCoeff2_ce0 = 1'b1;
    end else begin
        FiltCoeff2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        FiltCoeff3_ce0 = 1'b1;
    end else begin
        FiltCoeff3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        FiltCoeff4_ce0 = 1'b1;
    end else begin
        FiltCoeff4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        FiltCoeff5_ce0 = 1'b1;
    end else begin
        FiltCoeff5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        FiltCoeff_ce0 = 1'b1;
    end else begin
        FiltCoeff_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to8 = 1'b1;
    end else begin
        ap_idle_pp0_0to8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to8 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1117_ce = 1'b1;
    end else begin
        grp_fu_1117_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1126_ce = 1'b1;
    end else begin
        grp_fu_1126_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1135_ce = 1'b1;
    end else begin
        grp_fu_1135_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1144_ce = 1'b1;
    end else begin
        grp_fu_1144_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1153_ce = 1'b1;
    end else begin
        grp_fu_1153_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1162_ce = 1'b1;
    end else begin
        grp_fu_1162_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1171_ce = 1'b1;
    end else begin
        grp_fu_1171_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1179_ce = 1'b1;
    end else begin
        grp_fu_1179_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1187_ce = 1'b1;
    end else begin
        grp_fu_1187_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1195_ce = 1'b1;
    end else begin
        grp_fu_1195_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1204_ce = 1'b1;
    end else begin
        grp_fu_1204_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1213_ce = 1'b1;
    end else begin
        grp_fu_1213_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1222_ce = 1'b1;
    end else begin
        grp_fu_1222_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1230_ce = 1'b1;
    end else begin
        grp_fu_1230_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1238_ce = 1'b1;
    end else begin
        grp_fu_1238_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1246_ce = 1'b1;
    end else begin
        grp_fu_1246_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1257_ce = 1'b1;
    end else begin
        grp_fu_1257_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1268_ce = 1'b1;
    end else begin
        grp_fu_1268_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign FiltCoeff1_address0 = idxprom5_reg_1279;

assign FiltCoeff2_address0 = idxprom5_reg_1279_pp0_iter1_reg;

assign FiltCoeff3_address0 = idxprom5_reg_1279_pp0_iter2_reg;

assign FiltCoeff4_address0 = idxprom5_reg_1279_pp0_iter3_reg;

assign FiltCoeff5_address0 = idxprom5_reg_1279_pp0_iter4_reg;

assign FiltCoeff_address0 = idxprom5_fu_356_p1;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = select_ln301_fu_973_p3;

assign ap_return_1 = select_ln301_1_fu_1032_p3;

assign ap_return_2 = select_ln301_2_fu_1091_p3;

assign grp_fu_1117_p0 = grp_fu_1117_p00;

assign grp_fu_1117_p00 = tmp_reg_1293;

assign grp_fu_1117_p1 = sext_ln215_fu_820_p1;

assign grp_fu_1117_p2 = 24'd2048;

assign grp_fu_1126_p0 = grp_fu_1126_p00;

assign grp_fu_1126_p00 = tmp_1_reg_1323;

assign grp_fu_1126_p1 = sext_ln215_fu_820_p1;

assign grp_fu_1126_p2 = 24'd2048;

assign grp_fu_1135_p0 = grp_fu_1135_p00;

assign grp_fu_1135_p00 = tmp_2_reg_1353;

assign grp_fu_1135_p1 = sext_ln215_fu_820_p1;

assign grp_fu_1135_p2 = 24'd2048;

assign grp_fu_1144_p0 = grp_fu_1144_p00;

assign grp_fu_1144_p00 = select_ln215_3_reg_1298_pp0_iter1_reg;

assign grp_fu_1144_p1 = sext_ln215_1_fu_833_p1;

assign grp_fu_1153_p0 = grp_fu_1153_p00;

assign grp_fu_1153_p00 = select_ln215_17_reg_1328_pp0_iter1_reg;

assign grp_fu_1153_p1 = sext_ln215_1_fu_833_p1;

assign grp_fu_1162_p0 = grp_fu_1162_p00;

assign grp_fu_1162_p00 = select_ln215_31_reg_1358_pp0_iter1_reg;

assign grp_fu_1162_p1 = sext_ln215_1_fu_833_p1;

assign grp_fu_1171_p0 = grp_fu_1171_p00;

assign grp_fu_1171_p00 = select_ln215_7_reg_1303_pp0_iter2_reg;

assign grp_fu_1171_p1 = sext_ln215_2_fu_846_p1;

assign grp_fu_1179_p0 = grp_fu_1179_p00;

assign grp_fu_1179_p00 = select_ln215_21_reg_1333_pp0_iter2_reg;

assign grp_fu_1179_p1 = sext_ln215_2_fu_846_p1;

assign grp_fu_1187_p0 = grp_fu_1187_p00;

assign grp_fu_1187_p00 = select_ln215_35_reg_1363_pp0_iter2_reg;

assign grp_fu_1187_p1 = sext_ln215_2_fu_846_p1;

assign grp_fu_1195_p0 = grp_fu_1195_p00;

assign grp_fu_1195_p00 = select_ln215_10_reg_1308_pp0_iter3_reg;

assign grp_fu_1195_p1 = sext_ln215_3_fu_862_p1;

assign grp_fu_1204_p0 = grp_fu_1204_p00;

assign grp_fu_1204_p00 = select_ln215_24_reg_1338_pp0_iter3_reg;

assign grp_fu_1204_p1 = sext_ln215_3_fu_862_p1;

assign grp_fu_1213_p0 = grp_fu_1213_p00;

assign grp_fu_1213_p00 = select_ln215_38_reg_1368_pp0_iter3_reg;

assign grp_fu_1213_p1 = sext_ln215_3_fu_862_p1;

assign grp_fu_1222_p0 = grp_fu_1222_p00;

assign grp_fu_1222_p00 = select_ln215_12_reg_1313_pp0_iter4_reg;

assign grp_fu_1222_p1 = sext_ln215_4_fu_884_p1;

assign grp_fu_1230_p0 = grp_fu_1230_p00;

assign grp_fu_1230_p00 = select_ln215_26_reg_1343_pp0_iter4_reg;

assign grp_fu_1230_p1 = sext_ln215_4_fu_884_p1;

assign grp_fu_1238_p0 = grp_fu_1238_p00;

assign grp_fu_1238_p00 = select_ln215_40_reg_1373_pp0_iter4_reg;

assign grp_fu_1238_p1 = sext_ln215_4_fu_884_p1;

assign grp_fu_1246_p0 = grp_fu_1246_p00;

assign grp_fu_1246_p00 = select_ln215_13_reg_1318_pp0_iter5_reg;

assign grp_fu_1246_p1 = sext_ln215_5_fu_903_p1;

assign grp_fu_1257_p0 = grp_fu_1257_p00;

assign grp_fu_1257_p00 = select_ln215_27_reg_1348_pp0_iter5_reg;

assign grp_fu_1257_p1 = sext_ln215_5_fu_903_p1;

assign grp_fu_1268_p0 = grp_fu_1268_p00;

assign grp_fu_1268_p00 = select_ln215_41_reg_1378_pp0_iter5_reg;

assign grp_fu_1268_p1 = sext_ln215_5_fu_903_p1;

assign icmp_ln215_1_fu_395_p2 = ((p_read124 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln215_2_fu_401_p2 = ((p_read124 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln215_3_fu_407_p2 = ((p_read124 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_389_p2 = ((p_read124 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln861_1_fu_997_p2 = (($signed(tmp_6_fu_988_p4) > $signed(7'd0)) ? 1'b1 : 1'b0);

assign icmp_ln861_2_fu_1056_p2 = (($signed(tmp_8_fu_1047_p4) > $signed(7'd0)) ? 1'b1 : 1'b0);

assign icmp_ln861_fu_938_p2 = (($signed(tmp_4_fu_929_p4) > $signed(7'd0)) ? 1'b1 : 1'b0);

assign idx_fu_361_p2 = (p_read1_cast_fu_352_p1 + 3'd1);

assign idxprom5_fu_356_p1 = PhasesH_0_read;

assign or_ln215_1_fu_435_p2 = (icmp_ln215_fu_389_p2 | icmp_ln215_1_fu_395_p2);

assign or_ln215_2_fu_449_p2 = (or_ln215_fu_421_p2 | or_ln215_1_fu_435_p2);

assign or_ln215_3_fu_503_p2 = (icmp_ln215_2_fu_401_p2 | icmp_ln215_1_fu_395_p2);

assign or_ln215_fu_421_p2 = (icmp_ln215_3_fu_407_p2 | icmp_ln215_2_fu_401_p2);

assign or_ln301_1_fu_1026_p2 = (tmp_5_fu_981_p3 | icmp_ln861_1_fu_997_p2);

assign or_ln301_2_fu_1085_p2 = (tmp_7_fu_1040_p3 | icmp_ln861_2_fu_1056_p2);

assign or_ln301_fu_967_p2 = (tmp_3_fu_922_p3 | icmp_ln861_fu_938_p2);

assign p_read1_cast_fu_352_p1 = p_read124;

assign select_ln215_10_fu_517_p3 = ((or_ln215_3_fu_503_p2[0:0] == 1'b1) ? select_ln215_8_fu_495_p3 : select_ln215_9_fu_509_p3);

assign select_ln215_11_fu_525_p3 = ((icmp_ln215_fu_389_p2[0:0] == 1'b1) ? p_read15 : p_read21);

assign select_ln215_12_fu_533_p3 = ((icmp_ln215_1_fu_395_p2[0:0] == 1'b1) ? p_read18 : select_ln215_11_fu_525_p3);

assign select_ln215_13_fu_541_p3 = ((icmp_ln215_fu_389_p2[0:0] == 1'b1) ? p_read18 : p_read21);

assign select_ln215_14_fu_571_p3 = ((icmp_ln215_3_fu_407_p2[0:0] == 1'b1) ? p_read16 : p_read13);

assign select_ln215_15_fu_579_p3 = ((icmp_ln215_1_fu_395_p2[0:0] == 1'b1) ? p_read10 : p_read7);

assign select_ln215_16_fu_587_p3 = ((or_ln215_fu_421_p2[0:0] == 1'b1) ? select_ln215_14_fu_571_p3 : select_ln215_15_fu_579_p3);

assign select_ln215_17_fu_595_p3 = ((or_ln215_2_fu_449_p2[0:0] == 1'b1) ? select_ln215_16_fu_587_p3 : p_read22);

assign select_ln215_18_fu_603_p3 = ((icmp_ln215_3_fu_407_p2[0:0] == 1'b1) ? p_read19 : p_read16);

assign select_ln215_19_fu_611_p3 = ((icmp_ln215_1_fu_395_p2[0:0] == 1'b1) ? p_read13 : p_read10);

assign select_ln215_1_fu_427_p3 = ((icmp_ln215_1_fu_395_p2[0:0] == 1'b1) ? p_read9 : p_read6);

assign select_ln215_20_fu_619_p3 = ((or_ln215_fu_421_p2[0:0] == 1'b1) ? select_ln215_18_fu_603_p3 : select_ln215_19_fu_611_p3);

assign select_ln215_21_fu_627_p3 = ((or_ln215_2_fu_449_p2[0:0] == 1'b1) ? select_ln215_20_fu_619_p3 : p_read22);

assign select_ln215_22_fu_635_p3 = ((icmp_ln215_2_fu_401_p2[0:0] == 1'b1) ? p_read19 : p_read16);

assign select_ln215_23_fu_643_p3 = ((icmp_ln215_fu_389_p2[0:0] == 1'b1) ? p_read13 : p_read22);

assign select_ln215_24_fu_651_p3 = ((or_ln215_3_fu_503_p2[0:0] == 1'b1) ? select_ln215_22_fu_635_p3 : select_ln215_23_fu_643_p3);

assign select_ln215_25_fu_659_p3 = ((icmp_ln215_fu_389_p2[0:0] == 1'b1) ? p_read16 : p_read22);

assign select_ln215_26_fu_667_p3 = ((icmp_ln215_1_fu_395_p2[0:0] == 1'b1) ? p_read19 : select_ln215_25_fu_659_p3);

assign select_ln215_27_fu_675_p3 = ((icmp_ln215_fu_389_p2[0:0] == 1'b1) ? p_read19 : p_read22);

assign select_ln215_28_fu_705_p3 = ((icmp_ln215_3_fu_407_p2[0:0] == 1'b1) ? p_read17 : p_read14);

assign select_ln215_29_fu_713_p3 = ((icmp_ln215_1_fu_395_p2[0:0] == 1'b1) ? p_read11 : p_read8);

assign select_ln215_2_fu_441_p3 = ((or_ln215_fu_421_p2[0:0] == 1'b1) ? select_ln215_fu_413_p3 : select_ln215_1_fu_427_p3);

assign select_ln215_30_fu_721_p3 = ((or_ln215_fu_421_p2[0:0] == 1'b1) ? select_ln215_28_fu_705_p3 : select_ln215_29_fu_713_p3);

assign select_ln215_31_fu_729_p3 = ((or_ln215_2_fu_449_p2[0:0] == 1'b1) ? select_ln215_30_fu_721_p3 : p_read23);

assign select_ln215_32_fu_737_p3 = ((icmp_ln215_3_fu_407_p2[0:0] == 1'b1) ? p_read20 : p_read17);

assign select_ln215_33_fu_745_p3 = ((icmp_ln215_1_fu_395_p2[0:0] == 1'b1) ? p_read14 : p_read11);

assign select_ln215_34_fu_753_p3 = ((or_ln215_fu_421_p2[0:0] == 1'b1) ? select_ln215_32_fu_737_p3 : select_ln215_33_fu_745_p3);

assign select_ln215_35_fu_761_p3 = ((or_ln215_2_fu_449_p2[0:0] == 1'b1) ? select_ln215_34_fu_753_p3 : p_read23);

assign select_ln215_36_fu_769_p3 = ((icmp_ln215_2_fu_401_p2[0:0] == 1'b1) ? p_read20 : p_read17);

assign select_ln215_37_fu_777_p3 = ((icmp_ln215_fu_389_p2[0:0] == 1'b1) ? p_read14 : p_read23);

assign select_ln215_38_fu_785_p3 = ((or_ln215_3_fu_503_p2[0:0] == 1'b1) ? select_ln215_36_fu_769_p3 : select_ln215_37_fu_777_p3);

assign select_ln215_39_fu_793_p3 = ((icmp_ln215_fu_389_p2[0:0] == 1'b1) ? p_read17 : p_read23);

assign select_ln215_3_fu_455_p3 = ((or_ln215_2_fu_449_p2[0:0] == 1'b1) ? select_ln215_2_fu_441_p3 : p_read21);

assign select_ln215_40_fu_801_p3 = ((icmp_ln215_1_fu_395_p2[0:0] == 1'b1) ? p_read20 : select_ln215_39_fu_793_p3);

assign select_ln215_41_fu_809_p3 = ((icmp_ln215_fu_389_p2[0:0] == 1'b1) ? p_read20 : p_read23);

assign select_ln215_4_fu_463_p3 = ((icmp_ln215_3_fu_407_p2[0:0] == 1'b1) ? p_read18 : p_read15);

assign select_ln215_5_fu_471_p3 = ((icmp_ln215_1_fu_395_p2[0:0] == 1'b1) ? p_read12 : p_read9);

assign select_ln215_6_fu_479_p3 = ((or_ln215_fu_421_p2[0:0] == 1'b1) ? select_ln215_4_fu_463_p3 : select_ln215_5_fu_471_p3);

assign select_ln215_7_fu_487_p3 = ((or_ln215_2_fu_449_p2[0:0] == 1'b1) ? select_ln215_6_fu_479_p3 : p_read21);

assign select_ln215_8_fu_495_p3 = ((icmp_ln215_2_fu_401_p2[0:0] == 1'b1) ? p_read18 : p_read15);

assign select_ln215_9_fu_509_p3 = ((icmp_ln215_fu_389_p2[0:0] == 1'b1) ? p_read12 : p_read21);

assign select_ln215_fu_413_p3 = ((icmp_ln215_3_fu_407_p2[0:0] == 1'b1) ? p_read15 : p_read12);

assign select_ln301_1_fu_1032_p3 = ((or_ln301_1_fu_1026_p2[0:0] == 1'b1) ? select_ln301_4_fu_1018_p3 : trunc_ln301_1_fu_1003_p4);

assign select_ln301_2_fu_1091_p3 = ((or_ln301_2_fu_1085_p2[0:0] == 1'b1) ? select_ln301_5_fu_1077_p3 : trunc_ln301_2_fu_1062_p4);

assign select_ln301_3_fu_959_p3 = ((xor_ln301_fu_953_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln301_4_fu_1018_p3 = ((xor_ln301_1_fu_1012_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln301_5_fu_1077_p3 = ((xor_ln301_2_fu_1071_p2[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln301_fu_973_p3 = ((or_ln301_fu_967_p2[0:0] == 1'b1) ? select_ln301_3_fu_959_p3 : trunc_ln3_fu_944_p4);

assign sext_ln215_1_fu_833_p1 = $signed(FiltCoeff1_q0);

assign sext_ln215_2_fu_846_p1 = $signed(FiltCoeff2_q0);

assign sext_ln215_3_fu_862_p1 = $signed(FiltCoeff3_q0);

assign sext_ln215_4_fu_884_p1 = $signed(FiltCoeff4_q0);

assign sext_ln215_5_fu_903_p1 = $signed(FiltCoeff5_q0);

assign sext_ln215_fu_820_p1 = $signed(FiltCoeff_q0);

assign tmp_3_fu_922_p3 = grp_fu_1246_p3[32'd26];

assign tmp_4_fu_929_p4 = {{grp_fu_1246_p3[26:20]}};

assign tmp_5_fu_981_p3 = grp_fu_1257_p3[32'd26];

assign tmp_6_fu_988_p4 = {{grp_fu_1257_p3[26:20]}};

assign tmp_7_fu_1040_p3 = grp_fu_1268_p3[32'd26];

assign tmp_8_fu_1047_p4 = {{grp_fu_1268_p3[26:20]}};

assign trunc_ln301_1_fu_1003_p4 = {{grp_fu_1257_p3[19:12]}};

assign trunc_ln301_2_fu_1062_p4 = {{grp_fu_1268_p3[19:12]}};

assign trunc_ln3_fu_944_p4 = {{grp_fu_1246_p3[19:12]}};

assign xor_ln301_1_fu_1012_p2 = (tmp_5_fu_981_p3 ^ 1'd1);

assign xor_ln301_2_fu_1071_p2 = (tmp_7_fu_1040_p3 ^ 1'd1);

assign xor_ln301_fu_953_p2 = (tmp_3_fu_922_p3 ^ 1'd1);

always @ (posedge ap_clk) begin
    idxprom5_reg_1279[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    idxprom5_reg_1279_pp0_iter1_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    idxprom5_reg_1279_pp0_iter2_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    idxprom5_reg_1279_pp0_iter3_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    idxprom5_reg_1279_pp0_iter4_reg[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //bd_0837_hsc_0_hscale_polyphase
