@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Mar 22 15:11:37 -0400 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 1814c4d5952d4bc092476e99aecaed19 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L work -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot testPatternGen2_behav xil_defaultlib.testPatternGen2 xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 1814c4d5952d4bc092476e99aecaed19 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L work -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot testPatternGen2_behav xil_defaultlib.testPatternGen2 xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
