# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/atelier4Constraints.xdc

# Block Designs: bd/atelier4/atelier4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4 || ORIG_REF_NAME==atelier4} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_axi_vdma_0_0/atelier4_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_axi_vdma_0_0 || ORIG_REF_NAME==atelier4_axi_vdma_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_clk_wiz_0_0/atelier4_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_clk_wiz_0_0 || ORIG_REF_NAME==atelier4_clk_wiz_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_mycolorRegister_0_0/atelier4_mycolorRegister_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_mycolorRegister_0_0 || ORIG_REF_NAME==atelier4_mycolorRegister_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_pixelDataToVideoStre_0_3/atelier4_pixelDataToVideoStre_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_pixelDataToVideoStre_0_3 || ORIG_REF_NAME==atelier4_pixelDataToVideoStre_0_3} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_proc_sys_reset_0_0/atelier4_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_proc_sys_reset_0_0 || ORIG_REF_NAME==atelier4_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_processing_system7_0_0/atelier4_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_processing_system7_0_0 || ORIG_REF_NAME==atelier4_processing_system7_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_rgb2dvi_0_0/atelier4_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_rgb2dvi_0_0 || ORIG_REF_NAME==atelier4_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_smartconnect_0_0/atelier4_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_smartconnect_0_0 || ORIG_REF_NAME==atelier4_smartconnect_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_smartconnect_0_1/atelier4_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_smartconnect_0_1 || ORIG_REF_NAME==atelier4_smartconnect_0_1} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_testPatternGen2_0_0/atelier4_testPatternGen2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_testPatternGen2_0_0 || ORIG_REF_NAME==atelier4_testPatternGen2_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_v_axi4s_vid_out_0_0/atelier4_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==atelier4_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_v_proc_ss_0_0/atelier4_v_proc_ss_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_v_proc_ss_0_0 || ORIG_REF_NAME==atelier4_v_proc_ss_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_v_tc_0_0/atelier4_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_v_tc_0_0 || ORIG_REF_NAME==atelier4_v_tc_0_0} -quiet] -quiet

# XDC: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/atelier4_ooc.xdc
