@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Mar 22 15:11:13 -0400 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim testPatternGen2_behav -key {Behavioral:sim_1:Functional:testPatternGen2} -tclbatch testPatternGen2.tcl -protoinst "protoinst_files/bd_de31.protoinst" -protoinst "protoinst_files/bd_1ef0.protoinst" -protoinst "protoinst_files/bd_0cc7.protoinst" -protoinst "protoinst_files/bd_0837.protoinst" -protoinst "protoinst_files/atelier4.protoinst" -view C:/Travail/s4InfoAtelier4/atelier4_wrapper_behav.wcfg -log simulate.log"
call xsim  testPatternGen2_behav -key {Behavioral:sim_1:Functional:testPatternGen2} -tclbatch testPatternGen2.tcl -protoinst "protoinst_files/bd_de31.protoinst" -protoinst "protoinst_files/bd_1ef0.protoinst" -protoinst "protoinst_files/bd_0cc7.protoinst" -protoinst "protoinst_files/bd_0837.protoinst" -protoinst "protoinst_files/atelier4.protoinst" -view C:/Travail/s4InfoAtelier4/atelier4_wrapper_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
