# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo-Z7-Master.xdc

# Block Designs: bd/nomPertinent/nomPertinent.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nomPertinent || ORIG_REF_NAME==nomPertinent} -quiet] -quiet

# IP: bd/nomPertinent/ip/nomPertinent_processing_system7_0_0/nomPertinent_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nomPertinent_processing_system7_0_0 || ORIG_REF_NAME==nomPertinent_processing_system7_0_0} -quiet] -quiet

# IP: bd/nomPertinent/ip/nomPertinent_xbar_0/nomPertinent_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nomPertinent_xbar_0 || ORIG_REF_NAME==nomPertinent_xbar_0} -quiet] -quiet

# IP: bd/nomPertinent/ip/nomPertinent_axi_interconnect_0_0/nomPertinent_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nomPertinent_axi_interconnect_0_0 || ORIG_REF_NAME==nomPertinent_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/nomPertinent/ip/nomPertinent_axi_gpio_0_0/nomPertinent_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nomPertinent_axi_gpio_0_0 || ORIG_REF_NAME==nomPertinent_axi_gpio_0_0} -quiet] -quiet

# IP: bd/nomPertinent/ip/nomPertinent_PmodJSTK2_0_0/nomPertinent_PmodJSTK2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nomPertinent_PmodJSTK2_0_0 || ORIG_REF_NAME==nomPertinent_PmodJSTK2_0_0} -quiet] -quiet

# IP: bd/nomPertinent/ip/nomPertinent_rst_ps7_0_50M_0/nomPertinent_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nomPertinent_rst_ps7_0_50M_0 || ORIG_REF_NAME==nomPertinent_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/nomPertinent/ip/nomPertinent_auto_pc_0/nomPertinent_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nomPertinent_auto_pc_0 || ORIG_REF_NAME==nomPertinent_auto_pc_0} -quiet] -quiet

# XDC: c:/S3/project_1/project_1.gen/sources_1/bd/nomPertinent/nomPertinent_ooc.xdc
