# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Travail/s4InfoAtelier4/s4InfoAtelier4.srcs/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/atelier4_v_proc_ss_0_0.xci
# IP: The module: 'atelier4_v_proc_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/bd_0837.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837 || ORIG_REF_NAME==bd_0837} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_0/bd_0837_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_smartconnect_0_0 || ORIG_REF_NAME==bd_0837_smartconnect_0_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/bd_0837_vsc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_vsc_0 || ORIG_REF_NAME==bd_0837_vsc_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/bd_0837_hsc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_hsc_0 || ORIG_REF_NAME==bd_0837_hsc_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/bd_0837_input_size_set_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_input_size_set_0 || ORIG_REF_NAME==bd_0837_input_size_set_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_4/bd_0837_rst_axis_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_rst_axis_0 || ORIG_REF_NAME==bd_0837_rst_axis_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0837_reset_sel_axis_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_reset_sel_axis_0 || ORIG_REF_NAME==bd_0837_reset_sel_axis_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0837_axis_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_axis_register_slice_0_0 || ORIG_REF_NAME==bd_0837_axis_register_slice_0_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_7/bd_0837_axis_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_axis_fifo_0 || ORIG_REF_NAME==bd_0837_axis_fifo_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_8/bd_0837_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_xlslice_0_0 || ORIG_REF_NAME==bd_0837_xlslice_0_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_9/bd_0837_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_xlslice_1_0 || ORIG_REF_NAME==bd_0837_xlslice_1_0} -quiet] -quiet

# XDC: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/bd_0837_ooc.xdc

# XDC: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/atelier4_v_proc_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'atelier4_v_proc_ss_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Travail/s4InfoAtelier4/s4InfoAtelier4.srcs/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/atelier4_v_proc_ss_0_0.xci
# IP: The module: 'atelier4_v_proc_ss_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/bd_0837.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837 || ORIG_REF_NAME==bd_0837} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_0/bd_0837_smartconnect_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_smartconnect_0_0 || ORIG_REF_NAME==bd_0837_smartconnect_0_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/bd_0837_vsc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_vsc_0 || ORIG_REF_NAME==bd_0837_vsc_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/bd_0837_hsc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_hsc_0 || ORIG_REF_NAME==bd_0837_hsc_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/bd_0837_input_size_set_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_input_size_set_0 || ORIG_REF_NAME==bd_0837_input_size_set_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_4/bd_0837_rst_axis_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_rst_axis_0 || ORIG_REF_NAME==bd_0837_rst_axis_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0837_reset_sel_axis_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_reset_sel_axis_0 || ORIG_REF_NAME==bd_0837_reset_sel_axis_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0837_axis_register_slice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_axis_register_slice_0_0 || ORIG_REF_NAME==bd_0837_axis_register_slice_0_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_7/bd_0837_axis_fifo_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_axis_fifo_0 || ORIG_REF_NAME==bd_0837_axis_fifo_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_8/bd_0837_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_xlslice_0_0 || ORIG_REF_NAME==bd_0837_xlslice_0_0} -quiet] -quiet

# IP: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_9/bd_0837_xlslice_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_xlslice_1_0 || ORIG_REF_NAME==bd_0837_xlslice_1_0} -quiet] -quiet

# XDC: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/bd_0837_ooc.xdc

# XDC: c:/Travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/atelier4_v_proc_ss_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'atelier4_v_proc_ss_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
